# Generated by Django 5.2.11 on 2026-02-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletelemetry',
            name='anomaly_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vehicletelemetry',
            name='health_score',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='vehicletelemetry',
            name='severity',
            field=models.CharField(default='Healthy', max_length=20),
        ),
    ]
